<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0; net6.0; net8.0; net10.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<NullableReferenceTypes>true</NullableReferenceTypes>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>SKIT.JsonConv.SystemTextJson</PackageId>
		<PackageIcon>LOGO.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/fudiwei/DotNetCore.SKIT.JsonConv</PackageProjectUrl>
		<PackageTags>SKIT; JSON; JSON Converter; System.Text.Json</PackageTags>
		<Version>0.1.0</Version>
		<Description>为 System.Text.Json 扩展更多的 JSON 转换器。</Description>
		<Authors>Fu Diwei</Authors>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/fudiwei/DotNetCore.SKIT.JsonConv.git</RepositoryUrl>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<Deterministic>true</Deterministic>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
	</PropertyGroup>

	<ItemGroup>
		<None Include="../../LOGO.png" Pack="true" PackagePath="/" />
		<None Include="README.md" Pack="true" PackagePath="/" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401" PrivateAssets="All" />
		<PackageReference Include="System.Text.Json" Version="10.0.12" />
	</ItemGroup>

	<Import Project="..\SKIT.JsonConv.Shared\SKIT.JsonConv.Shared.projitems" Label="Shared" />

</Project>
